add: Channels model
practice-uffs/mural pull request #346
Opened 2021-07-16 12:57 UTC by alissonpeloso

Nessa issue foi criado um modelo "Channels" que contem user_id e fcm_token. O user id é um FK one-to-one que vai ligar cada usuário à um dispositivo com fcm_token. Esse token será utilizado para envio de notificações para os dispositivos movéis.

fix: #340

2021-07-20 15:42 UTC, Dovyski requested changes
Está ótimo!

2021-07-20 15:42 UTC, Dovyski commented on app/Channels.php
> +        return $this->hasOne('App\User');
```suggestion
        return $this->hasOne(User::class);
```

Em qualquer lugar que o nome de uma classe for necessária, usar `Nome::class` ao invés de uma string.

2021-07-20 15:42 UTC, Dovyski commented on app/User.php
> +        return $this->belongsTo('App\Channels');
```suggestion
        return $this->belongsTo(Channels::class);
```

Em qualquer lugar que o nome de uma classe for necessária, usar `Nome::class` ao invés de uma string.

2021-07-20 15:42 UTC, Dovyski commented on database/migrations/2021_07_08_111924_create_channels_table.php
> +            $table->foreign('user_id')->references('id')->on('users');
```suggestion
            $table->foreignId('user_id')->constrained();
```

Dica para escrever menos código.

2021-07-21 13:00 UTC, alissonpeloso commented
Sugestões commitadas, @Dovyski .

2021-07-21 14:07 UTC, Dovyski approved these changes
Excelente, obrigado! ❤️

2021-07-25 03:27 UTC, merged