432
practice-uffs/mural pull request #437
Opened 2022-03-08 07:15 UTC by CleissonVieira

Fix: #432 
Novo ícone/logo adicionado
![image](https://user-images.githubusercontent.com/29258164/157185749-adde9922-e807-4afe-af6c-8d73d6af99a3.png)
![image](https://user-images.githubusercontent.com/29258164/157185778-3e526199-f2ba-4cfa-8b6d-f6441713d485.png)
![image](https://user-images.githubusercontent.com/29258164/157185823-f5dbc7f4-9bf2-4348-a1f4-f425f3fce6ff.png)

2022-03-08 13:23 UTC, alissonpeloso commented
@CleissonVieira, lembra de me marcar como reviwer

2022-03-08 13:24 UTC, alissonpeloso commented
Ajustei o nome do PR também

2022-03-08 13:47 UTC, alissonpeloso requested changes
Não tá aparecendo a logo no mobile:

![image](https://user-images.githubusercontent.com/51202705/157250480-bacb4654-8be3-4cbe-8bc0-916de5f2d0f0.png)

2022-03-14 05:20 UTC, CleissonVieira commented
Logo ajustado
O CSS está um pouco confuso

![image](https://user-images.githubusercontent.com/29258164/158109529-8be28fdd-a64f-4c2b-b1fe-eca723c4440f.png)

2022-03-14 14:33 UTC, merged