fix: corrige os problemas do layout da tela de acompanhamento de pedidos
practice-uffs/mural pull request #442
Opened 2022-03-18 13:58 UTC by stefanimeneghetti

A tela de acompanhamento de pedidos era bem pouco responsiva e apresentava dificuldades de uso em vários os tamanhos, então eu ajustei o layout para um conjunto maior de tamanhos.

**Mobile:**
![image](https://user-images.githubusercontent.com/51202548/159014520-c40cfe2a-84bf-41d5-900f-4b98b6a5bdd3.png)

**Tamanho médio:**
![image](https://user-images.githubusercontent.com/51202548/159014859-7b49d20d-0b23-4b0c-a48c-90162799ff23.png)

**Desktop:**
![image](https://user-images.githubusercontent.com/51202548/159014977-fd215c68-deb4-4ef7-94f0-dcabc77e61b9.png)

Fix: #440

2022-03-21 11:08 UTC, alissonpeloso requested changes

2022-03-21 11:08 UTC, alissonpeloso commented on resources/views/order/list.blade.php
> +                                        <div class="avatar pr-3">
```suggestion
                                        <div class="avatar pr-3 pb-2">
```

2022-03-21 11:08 UTC, alissonpeloso commented on resources/views/order/list.blade.php
> +                                        <div class="avatar pr-3">
Coloquei um padding no bottom e achei mais agradável

2022-03-21 11:08 UTC, alissonpeloso commented on resources/views/order/list.blade.php
> +                    <thead class="d-flex flex-row w-auto">
Acho que dá pra manter essa linha de informação só no desktop, quando fica menor ele se agrupa e ocupa muito espaço

2022-03-21 11:10 UTC, alissonpeloso commented
Gostei muito da implementação, ficou muito mais agradável o layout no mobile. Só coloquei umas alterações que achei interessante, pouca coisa.

2022-03-21 13:57 UTC, stefanimeneghetti commented
Ajustes feitos

2022-03-22 12:24 UTC, alissonpeloso approved these changes

2022-03-22 12:24 UTC, merged